Fix incompatible types for list divider resource.
+ Error in SuperListview.java:64: `incompatible types:
  int cannot be converted to Drawable getList().setDivider(mDivider);`
+ This error was introduced through the merge in
  commit 9c93459df8769792a76b6da811b035c722d24a3d. Please review again!
+ The original implementation to support drawable list dividers can
  be found in commit 366b88e01a7bd13b0325fb729742573063ae3268.